// Comprehensive list of UK Universities
export const UK_UNIVERSITIES = [
  'University of Oxford',
  'University of Cambridge',
  'Imperial College London',
  'University College London (UCL)',
  'King\'s College London',
  'University of Edinburgh',
  'University of Manchester',
  'London School of Economics and Political Science (LSE)',
  'University of Bristol',
  'University of Warwick',
  'University of Glasgow',
  'Durham University',
  'University of Southampton',
  'University of Birmingham',
  'University of Leeds',
  'University of Sheffield',
  'University of Nottingham',
  'Queen Mary University of London',
  'Lancaster University',
  'University of York',
  'University of Exeter',
  'Cardiff University',
  'University of Bath',
  'University of Liverpool',
  'University of Reading',
  'University of Aberdeen',
  'University of St Andrews',
  'University of Sussex',
  'Loughborough University',
  'Newcastle University',
  'Royal Holloway, University of London',
  'University of Leicester',
  'University of Surrey',
  'Swansea University',
  'Queen\'s University Belfast',
  'University of Strathclyde',
  'University of East Anglia (UEA)',
  'City, University of London',
  'Heriot-Watt University',
  'Aston University',
  'University of Kent',
  'Coventry University',
  'University of Essex',
  'SOAS University of London',
  'University of Dundee',
  'Brunel University London',
  'Oxford Brookes University',
  'University of Stirling',
  'Goldsmiths, University of London',
  'Northumbria University',
  'University of Plymouth',
  'Keele University',
  'University of Portsmouth',
  'Bangor University',
  'Nottingham Trent University',
  'Bournemouth University',
  'University of Hull',
  'University of Lincoln',
  'De Montfort University',
  'Middlesex University',
  'University of the West of England',
  'Manchester Metropolitan University',
  'Birmingham City University',
  'University of Salford',
  'Robert Gordon University',
  'Sheffield Hallam University',
  'University of Greenwich',
  'University of Central Lancashire',
  'University of Westminster',
  'University of Huddersfield',
  'Anglia Ruskin University',
  'University of Brighton',
  'University of Hertfordshire',
  'University of Bradford',
  'Edge Hill University',
  'Liverpool John Moores University',
  'University of Roehampton',
  'University of Winchester',
  'Staffordshire University',
  'Ulster University',
  'Arts University Bournemouth',
  'University of Chester',
  'Cardiff Metropolitan University',
  'University of Derby',
  'University of Gloucestershire',
  'University of Northampton',
  'University of Sunderland',
  'University of Worcester',
  'Bath Spa University',
  'University of Bedfordshire',
  'University of Chichester',
  'University of the West of Scotland',
  'Glasgow Caledonian University',
  'Leeds Beckett University',
  'Canterbury Christ Church University',
  'Teesside University',
  'Aberystwyth University',
  'Abertay University',
  'Bishop Grosseteste University',
  'Buckinghamshire New University',
  'University of Cumbria',
  'Edinburgh Napier University',
  'Falmouth University',
  'University of East London',
  'Leeds Arts University',
  'University of South Wales',
  'London Metropolitan University',
  'London South Bank University',
  'Newman University',
  'University of Suffolk',
  'Norwich University of the Arts',
  'Plymouth Marjon University',
  'Queen Margaret University',
  'Ravensbourne University London',
  'Royal Agricultural University',
  'Solent University',
  'St Mary\'s University, Twickenham',
  'University of Wales Trinity Saint David',
  'University of Wolverhampton',
  'York St John University',
  'Wrexham University',
  'Regent\'s University London',
  'University of Bolton',
  'Birkbeck, University of London',
  'Cranfield University',
  'Harper Adams University',
  'Royal College of Art',
  'Royal Central School of Speech and Drama',
  'Guildhall School of Music and Drama',
  'Royal Academy of Music',
  'Royal College of Music',
  'Conservatoire for Dance and Drama',
  'Leeds Conservatoire',
  'Liverpool Institute for Performing Arts',
  'Royal Conservatoire of Scotland',
  'Trinity Laban Conservatoire of Music and Dance',
  'University of London',
  'The Open University',
  'Arden University',
  'BPP University',
  'University of Law',
  'Other',
].sort();
